buttons:
  '1':
    name: Next State
  '2':
    name: Prev State
  '3':
    name: Reset States
  '4':
    name: 'OFF'
    state:
      all: &id002
        funct: 'off'
  '5':
    name: RGB
    state:
      '3':
        funct: set_mode
        m: 0
        r: 200
      '4':
        funct: set_mode
        g: 200
        m: 0
      '6':
        b: 200
        funct: set_mode
        m: 0
  '6':
    name: btn6_name
  '7':
    name: All Rainbow
    state:
      all: &id001
        funct: set_mode
        m: 11
        s: 128
states:
- name: mood
  state:
    '1': *id001
    '2': *id001
    '3': *id001
    '4': *id001
    '5': *id001
    '6': *id001
    '7': *id001
    '8': *id001
- name: 'OFF'
  state:
    all: *id002
tables:
  '1': WeddingLight01
  '2': WeddingLight02
  '3': WeddingLight03
  '4': WeddingLight04
  '5': WeddingLight05
  '6': WeddingLight06
  '7': WeddingLight07
  '8': WeddingLight08
